version: '3'

services:
  com.service.taxcalculation.webapi:
    image: com.service.taxcalculation.webapi
    build:
      context: .
      dockerfile: Com.Service.TaxCalculation.WebApi/Dockerfile
    depends_on:
      - mssql

  mssql:
    image: microsoft/mssql-server-linux:latest