// <auto-generated />
using System;
using Com.Service.TaxCalculation.Lib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Com.Service.TaxCalculation.Lib.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20181002152354_init_taxCalculation")]
    partial class init_taxCalculation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Com.Service.TaxCalculation.Lib.Facade.Product.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<int>("TaxCode");

                    b.Property<string>("Type")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Com.Service.TaxCalculation.Lib.Facade.TaxCalculation.TaxCalculationDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Amount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Name");

                    b.Property<double?>("TaxAmount");

                    b.Property<int>("TaxCalculationId");

                    b.Property<int>("TaxCode");

                    b.Property<double?>("Total");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TaxCalculationId");

                    b.ToTable("TaxCalculationDetails");
                });

            modelBuilder.Entity("Com.Service.TaxCalculation.Lib.Facade.TaxCalculation.TaxCalculationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<double?>("GrandTotal");

                    b.Property<double?>("TotalAmount");

                    b.Property<double?>("TotalTaxAmount");

                    b.HasKey("Id");

                    b.ToTable("TaxCalculation");
                });

            modelBuilder.Entity("Com.Service.TaxCalculation.Lib.Facade.TaxCalculation.TaxCalculationDetailsModel", b =>
                {
                    b.HasOne("Com.Service.TaxCalculation.Lib.Facade.TaxCalculation.TaxCalculationModel", "TaxCalculation")
                        .WithMany("Details")
                        .HasForeignKey("TaxCalculationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
